modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="hardmode"
version="1.0.0"
displayName="Hardmode"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Kis Keve, MCreator"

[[dependencies.hardmode]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



